dist:     trusty    
sudo:     required  

language: c         
                    
os:    
    - linux
    - osx
    
compiler:
    - gcc
    - clang
    
before_script:
  - pip3 install --user cpplint
    
addons:
  apt:
    packages:
      - valgrind
      - cppcheck
      - make
      - cmake
      - python3
      - python3-pip



matrix:
    exclude:
        # вручную исключим ненужные элементы из матрицы сборки:
        - os:       osx
          compiler: gcc
          
          


script:
    # скрипт сборки и тестирования проекта:
    - gcc -std=c11 -Wall -Wpedantic -c ./libstatic.c
    - ar r libstatic.a libstatic.o
    - gcc -std=c11 -Wall -Wpedantic -c -fPIC libdynamic.c
    - gcc -shared -o libdynamic.so libdynamic.o
    - gcc -std=c11 -Wall -Wpedantic --coverage -c *.c
    - gcc -o zadanie_2_multithread_proga *.o -fprofile-arcs -ftest-coverage -g -L. -ldynamic -lstatic -Wl,-rpath,.
    - ./zadanie_2_multithread_proga
    - gcov *.c
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then valgrind --leak-check=full --show-leak-kinds=all ./zadanie_2_multithread_proga ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cppcheck --enable=warning,performance,information,style *.c *.h ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cpplint --filter=-readability,-build *.c ; fi
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
